### ISSUE TITLE
Add Functionality to Home Page

### ISSUE THREAD

**Issue by Adastros** [Adastros/audiophile#29]
### Dependencies
- #30

### Overview

The goal of this issue is to add functionality to buttons and links on the homepage. This issue will track the dependencies. 

### Action Items

- [x] Add functionality to the menu button
- [x] Add functionality for the "see product" buttons
- [x] Add functionality for the "shop link" component
- [x] Add functionality for the navigation link component
- [x] Add functionality for the cart button

### Resources/Instructions

- [React Router Documentation](https://reactrouter.com/en/main)
