### ISSUE TITLE
Create the Home Page for the Mobile View

### ISSUE THREAD

**Issue by Adastros** [Adastros/audiophile#5]
#### Initial Layout Issue Tracker
- #17
 
#### Styling Homepage Issue Tracker
- #18

#### Testing Homepage Tracker
- #27 

#### Homepage Functionality Tracker
- #29 

### Overview

The goal of this issue is to create the mobile view of the home page. 

### Action Items

- [x] Recreate the mobile view of the home page based on the figma wireframe while using the JSON data provided by the backend
- [x] Create animations and hover styles using the provided design system in the figma file
- [ ] Test and verify that the elements on the home page function as intended
  - [ ] If needed, develop Cypress tests to verify functionality

### Resources/Instructions

- [Cypress Documentation](https://docs.cypress.io/guides/overview/why-cypress)
- Refer to Figma design file provided by [Frontendmentor.io](https://www.frontendmentor.io/challenges/audiophile-ecommerce-website-C8cuSd_wx)
